[package]
name = "sledge"
version = "0.1.0"
description = "A playful pixel drawing tool"
authors = ["innsbluck"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.86.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
log = "0.4"
sysinfo = "0.34.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.5.1", features = [
    "devtools",
    "protocol-asset",
    "image-png",
] }
tauri-plugin-dialog = "2.2.1"
tauri-plugin-fs = "2.2.1"
tauri-plugin-shell = "2.2.1"
tauri-plugin-system-info = "2.0.9"
tauri-plugin-opener = "2.2.6"
image = "0.25.6"
dirs = "6.0.0"
uuid = { version = "1.17.0", features = ["v4"] }
url = "2"
tokio = { version = "1.46.1", features = ["full"] }
eframe = "0.29"
egui = "0.29"
winit = "0.30"
tauri-plugin-log = "2.6.0"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
profiling-procmacros = "1.0.16"
tauri-wasm = "0.2.0"

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.
