name: dev

on:
  push:
    branches: ['develop']

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # Node & Rust 環境セットアップ
      - uses: actions/setup-node@v4
        with: { node-version: 'latest' }

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup Rust cache environment
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        shell: bash

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm
        run: pnpm wasm:build

      - name: install frontend dependencies
        run: pnpm install

      # Tauri Build Only
      - uses: tauri-apps/tauri-action@v0
        id: tauri-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCCACHE_GHA_ENABLED: 'true'
          RUSTC_WRAPPER: 'sccache'
        with:
          projectPath: './apps/sledge'
          args: ${{ matrix.args }}

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: binaries-linux
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.deb
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.rpm
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.AppImage
          retention-days: 3

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'macos-latest'
        with:
          name: binaries-macos
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.dmg
          retention-days: 3

      - name: Upload dev artifacts
        uses: actions/upload-artifact@v4
        if: matrix.platform == 'windows-latest'
        with:
          name: binaries-windows
          path: |
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.exe
            ${{ github.workspace }}/apps/sledge/src-tauri/target/release/bundle/**/*.msi
          retention-days: 3
