name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-prealpha'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # Node & Rust 環境セットアップ
      - uses: actions/setup-node@v4
        with: { node-version: 'latest' }
      - uses: dtolnay/rust-toolchain@stable
      - uses: pnpm/action-setup@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build wasm
        run: pnpm wasm:build

      - name: install frontend dependencies
        run: pnpm install

      # Tauri Build + Release Upload
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ github.ref_name }}
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          projectPath: './apps/sledge'
          releaseDraft: true
          prerelease: false
